<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EventoFestividadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 🚨 NOTA IMPORTANTE: Las fechas de Carnaval, Semana Santa y Corpus Christi son variables.
        // Se usan fechas de referencia para el año 2024 o 2025.

        // Mapeo de IDs de Destinos creados en el seeder anterior para asegurar la conexión.
        // Se asume que estos IDs existen. Si no, se pueden usar valores por defecto (ej. 1 para Plaza de Armas).

        // Destinos principales (Asumiendo IDs incrementales desde el anterior seeder)
        $idPlazaArmas = DB::table('destinos')->where('nombre_destino', 'Plaza de Armas de Tarma')->value('id_destino') ?? 1;
        $idCatedral = DB::table('destinos')->where('nombre_destino', 'Catedral de Santa Ana de Tarma')->value('id_destino') ?? 2;
        $idMuseoOdria = DB::table('destinos')->where('nombre_destino', 'Museo Regional Manuel A. Odría')->value('id_destino') ?? 3;
        $idTarmatambo = DB::table('destinos')->where('nombre_destino', 'Sitio Arqueológico de Tarmatambo')->value('id_destino') ?? 4;
        $idCapillaCarcel = DB::table('destinos')->where('nombre_destino', 'Capilla del Señor de la Cárcel')->value('id_destino') ?? 6;
        $idGrutaHuagapo = DB::table('destinos')->where('nombre_destino', 'Gruta de Huagapo (Distrito de Palcamayo)')->value('id_destino') ?? 7;
        $idCampinaFlores = DB::table('destinos')->where('nombre_destino', 'Campiña de Sacsamarca (Valle de las Flores)')->value('id_destino') ?? 8;
        $idCachipuquio = DB::table('destinos')->where('nombre_destino', 'Cachipuquio (Manantiales Salinos - San Pedro de Cajas)')->value('id_destino') ?? 9;
        $idSantuarioMuruhuay = DB::table('destinos')->where('nombre_destino', 'Santuario del Señor de Muruhuay (Distrito de Acobamba)')->value('id_destino') ?? 12;
        $idSanPedroCajas = DB::table('destinos')->where('nombre_destino', 'Distrito de San Pedro de Cajas (Cuna del Tapiz)')->value('id_destino') ?? 13;
        $idHaciendaFlorida = DB::table('destinos')->where('nombre_destino', 'Hacienda de Sacsamarca / Ex-Hacienda La Florida')->value('id_destino') ?? 14;

        // IDs para Distritos Específicos (si no fueron creados como destinos genéricos, se asocia a la Plaza de Armas o se asume el ID del destino más representativo del distrito)
        $idDistritoPalcamayo = DB::table('destinos')->where('nombre_destino', 'Gruta de Huagapo (Distrito de Palcamayo)')->value('id_destino') ?? $idPlazaArmas;
        $idDistritoHuaricolca = DB::table('destinos')->where('nombre_destino', 'Ruinas Arqueológicas de Paca')->value('id_destino') ?? $idPlazaArmas; // Paca está cerca de Huaricolca
        $idDistritoHuasahuasi = $idPlazaArmas; // Usar ID de Plaza si no hay uno específico
        $idDistritoPalca = $idPlazaArmas;
        $idDistritoTapo = $idPlazaArmas;

        DB::table('evento_festividades')->insert([

            // --- 1. Eventos de la Ciudad de Tarma (Urbano) ---
            [
                'nombre_evento' => 'Carnaval Tarmeño: La Muliza y Chonguinada',
                'tipo_evento' => 'Folclórico/Danza',
                'fecha_inicio' => '2025-03-01', // Fecha Movible (Martes de Carnaval aprox.)
                'fecha_fin' => '2025-03-05',
                'lugar_asociado' => $idPlazaArmas,
                'afluencia_esperada' => 10000,
                'costo_entrada' => 0.0,
                'valor_cultural' => 9,
                'palabras_clave' => 'carnaval,muliza,chonguinada,danza,febrero,marzo,comparsas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Semana Santa Tarmeña (Alfombras de Flores)',
                'tipo_evento' => 'Religioso/Artesanal',
                'fecha_inicio' => '2025-04-13', // Domingo de Ramos 2025
                'fecha_fin' => '2025-04-20', // Domingo de Resurrección
                'lugar_asociado' => $idCatedral,
                'afluencia_esperada' => 30000,
                'costo_entrada' => 0.0,
                'valor_cultural' => 10,
                'palabras_clave' => 'Semana Santa,procesión,alfombras de flores,pasión,cristo,flores',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Corpus Christi y Octava',
                'tipo_evento' => 'Religioso',
                'fecha_inicio' => '2025-06-19', // Jueves Movible (Aprox)
                'fecha_fin' => '2025-06-26',
                'lugar_asociado' => $idCatedral,
                'afluencia_esperada' => 5000,
                'costo_entrada' => 0.0,
                'valor_cultural' => 8,
                'palabras_clave' => 'Corpus,eucaristía,procesión,religión,junio',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Día Central de la Virgen de las Mercedes',
                'tipo_evento' => 'Religioso/Patronal',
                'fecha_inicio' => '2025-09-24',
                'fecha_fin' => '2025-09-24',
                'lugar_asociado' => $idCapillaCarcel,
                'afluencia_esperada' => 1500,
                'costo_entrada' => 0.0,
                'valor_cultural' => 7,
                'palabras_clave' => 'virgen,patrona,procesión,septiembre,carcel',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Aniversario de la Provincia de Tarma',
                'tipo_evento' => 'Cívico/Protocolar',
                'fecha_inicio' => '2025-07-26',
                'fecha_fin' => '2025-07-29',
                'lugar_asociado' => $idPlazaArmas,
                'afluencia_esperada' => 8000,
                'costo_entrada' => 0.0,
                'valor_cultural' => 7,
                'palabras_clave' => 'aniversario,fiestas patrias,desfile,Julio,serenata',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Feria Agroindustrial y Artesanal Expo Tarma',
                'tipo_evento' => 'Feria/Exposición',
                'fecha_inicio' => '2025-07-26',
                'fecha_fin' => '2025-07-29',
                'lugar_asociado' => $idPlazaArmas, // o un campo ferial cercano a la ciudad
                'afluencia_esperada' => 5000,
                'costo_entrada' => 0.0,
                'valor_cultural' => 6,
                'palabras_clave' => 'feria,agrícola,artesanía,ganado,Julio,expo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Día de Todos los Santos (Preparación de T\'anta Wawas)',
                'tipo_evento' => 'Religioso/Gastronómico',
                'fecha_inicio' => '2025-11-01',
                'fecha_fin' => '2025-11-02',
                'lugar_asociado' => $idCatedral, // Evento familiar, pero la ciudad es el centro
                'afluencia_esperada' => 4000,
                'costo_entrada' => 0.0,
                'valor_cultural' => 8,
                'palabras_clave' => 'difuntos,pan,tanta wawa,tradición,noviembre,gastronomía',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // --- 2. Eventos por Distritos y Atractivos Específicos ---

            // **Distrito de Acobamba / Santuario de Muruhuay**
            [
                'nombre_evento' => 'Fiesta Patronal del Señor de Muruhuay',
                'tipo_evento' => 'Procesión religiosa',
                'fecha_inicio' => '2025-05-01',
                'fecha_fin' => '2025-05-31',
                'lugar_asociado' => $idSantuarioMuruhuay,
                'afluencia_esperada' => 15000,
                'costo_entrada' => 0.0,
                'valor_cultural' => 9,
                'palabras_clave' => 'peregrinación,danzas folclóricas,Muruhuay,mayo,Acobamba',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Bautizo de Muruhuay (Día Central)',
                'tipo_evento' => 'Religioso/Folclórico',
                'fecha_inicio' => '2025-05-03',
                'fecha_fin' => '2025-05-03',
                'lugar_asociado' => $idSantuarioMuruhuay,
                'afluencia_esperada' => 20000,
                'costo_entrada' => 0.0,
                'valor_cultural' => 10,
                'palabras_clave' => 'Día central,milagro,bandas,folclore,Acobamba,mayo',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // **Distrito de San Pedro de Cajas**
            [
                'nombre_evento' => 'Concurso de Tapices y Artesanía',
                'tipo_evento' => 'Concurso Artesanal',
                'fecha_inicio' => '2025-06-27',
                'fecha_fin' => '2025-06-29',
                'lugar_asociado' => $idSanPedroCajas, // Plaza/Galerías
                'afluencia_esperada' => 3000,
                'costo_entrada' => 0.0,
                'valor_cultural' => 9,
                'palabras_clave' => 'tapices,artesanía,textil,lana,San Pedro de Cajas,junio',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Fiesta Patronal de San Pedro y San Pablo',
                'tipo_evento' => 'Religioso/Patronal',
                'fecha_inicio' => '2025-06-29',
                'fecha_fin' => '2025-06-30',
                'lugar_asociado' => $idSanPedroCajas,
                'afluencia_esperada' => 4000,
                'costo_entrada' => 0.0,
                'valor_cultural' => 8,
                'palabras_clave' => 'patronal,San Pedro,junio,danza,costumbrista',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Limpieza de las Pozas de Cachipuquio',
                'tipo_evento' => 'Costumbrista/Comunal',
                'fecha_inicio' => '2025-07-15',
                'fecha_fin' => '2025-07-15',
                'lugar_asociado' => $idCachipuquio,
                'afluencia_esperada' => 500,
                'costo_entrada' => 0.0,
                'valor_cultural' => 7,
                'palabras_clave' => 'cachipuquio,agua salada,tradición,limpieza,julio',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // **Distrito de Palcamayo / Gruta de Huagapo**
            [
                'nombre_evento' => 'Aniversario del Distrito de Palcamayo',
                'tipo_evento' => 'Cívico/Folclórico',
                'fecha_inicio' => '2025-01-01',
                'fecha_fin' => '2025-01-03',
                'lugar_asociado' => $idDistritoPalcamayo,
                'afluencia_esperada' => 2000,
                'costo_entrada' => 0.0,
                'valor_cultural' => 7,
                'palabras_clave' => 'aniversario,Palcamayo,enero,desfile,fiesta',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Ruta de Aventura y Espeleología Huagapo',
                'tipo_evento' => 'Deportivo/Aventura',
                'fecha_inicio' => '2025-08-01',
                'fecha_fin' => '2025-08-03',
                'lugar_asociado' => $idGrutaHuagapo,
                'afluencia_esperada' => 800,
                'costo_entrada' => 15.0, // Costo de guía y equipo
                'valor_cultural' => 6,
                'palabras_clave' => 'espeleología,Huagapo,cueva,agosto,turismo de aventura',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // **Distrito de Huasahuasi**
            [
                'nombre_evento' => 'Fiesta de San Juan Bautista (Huasahuasi)',
                'tipo_evento' => 'Religioso/Patronal',
                'fecha_inicio' => '2025-06-24',
                'fecha_fin' => '2025-06-26',
                'lugar_asociado' => $idDistritoHuasahuasi,
                'afluencia_esperada' => 2500,
                'costo_entrada' => 0.0,
                'valor_cultural' => 7,
                'palabras_clave' => 'San Juan,Huasahuasi,junio,danzas,gastronomía',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Festival de la Naranja y Productos de Selva Alta',
                'tipo_evento' => 'Feria/Gastronómico',
                'fecha_inicio' => '2025-09-05',
                'fecha_fin' => '2025-09-08',
                'lugar_asociado' => $idDistritoHuasahuasi,
                'afluencia_esperada' => 1500,
                'costo_entrada' => 0.0,
                'valor_cultural' => 6,
                'palabras_clave' => 'naranja,cítricos,selva alta,Huasahuasi,septiembre,frutas',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // **Distrito de Huaricolca**
            [
                'nombre_evento' => 'Fiesta de la Cruces de Huaricolca',
                'tipo_evento' => 'Religioso/Andino',
                'fecha_inicio' => '2025-05-01',
                'fecha_fin' => '2025-05-03',
                'lugar_asociado' => $idDistritoHuaricolca,
                'afluencia_esperada' => 900,
                'costo_entrada' => 0.0,
                'valor_cultural' => 7,
                'palabras_clave' => 'cruces,mayo,Huaricolca,danza,rito',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Día del Ganadero y Festival de la Leche',
                'tipo_evento' => 'Feria/Económico',
                'fecha_inicio' => '2025-08-20',
                'fecha_fin' => '2025-08-22',
                'lugar_asociado' => $idDistritoHuaricolca,
                'afluencia_esperada' => 600,
                'costo_entrada' => 0.0,
                'valor_cultural' => 6,
                'palabras_clave' => 'ganado,leche,queso,agosto,altoandino,Huaricolca',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // **Distrito de Palca**
            [
                'nombre_evento' => 'Fiesta Patronal de Santo Domingo de Guzmán',
                'tipo_evento' => 'Religioso/Patronal',
                'fecha_inicio' => '2025-08-04',
                'fecha_fin' => '2025-08-07',
                'lugar_asociado' => $idDistritoPalca,
                'afluencia_esperada' => 1200,
                'costo_entrada' => 0.0,
                'valor_cultural' => 7,
                'palabras_clave' => 'Santo Domingo,agosto,Palca,danzas,patronal',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // **Distrito de Tapo**
            [
                'nombre_evento' => 'Día de la Santísima Trinidad (Tapo)',
                'tipo_evento' => 'Religioso',
                'fecha_inicio' => '2025-06-08', // Domingo Movible (Aprox)
                'fecha_fin' => '2025-06-09',
                'lugar_asociado' => $idDistritoTapo,
                'afluencia_esperada' => 700,
                'costo_entrada' => 0.0,
                'valor_cultural' => 6,
                'palabras_clave' => 'trinidad,junio,Tapo,procesión',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // --- 3. Eventos Especiales y Estacionales (Recurrentes) ---
            [
                'nombre_evento' => 'Inti Raymi Tarmeño (Representación en Tarmatambo)',
                'tipo_evento' => 'Histórico/Representación',
                'fecha_inicio' => '2025-06-24',
                'fecha_fin' => '2025-06-24',
                'lugar_asociado' => $idTarmatambo,
                'afluencia_esperada' => 3500,
                'costo_entrada' => 5.0,
                'valor_cultural' => 8,
                'palabras_clave' => 'Inti Raymi,inca,Tarmatambo,sol,junio,representación',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Festival Gastronómico de la Pachamanca',
                'tipo_evento' => 'Gastronómico',
                'fecha_inicio' => '2025-03-29', // Se realiza en distintas fechas, usamos el Domingo de Ramos como ejemplo
                'fecha_fin' => '2025-03-30',
                'lugar_asociado' => $idPlazaArmas,
                'afluencia_esperada' => 5000,
                'costo_entrada' => 0.0, // Venta de platos
                'valor_cultural' => 7,
                'palabras_clave' => 'pachamanca,gastronomía,comida andina,carne,tradicional',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Temporada Alta de Venta de Flores (Día de los Muertos)',
                'tipo_evento' => 'Comercial/Estacional',
                'fecha_inicio' => '2025-10-28',
                'fecha_fin' => '2025-11-02',
                'lugar_asociado' => $idCampinaFlores,
                'afluencia_esperada' => 7000,
                'costo_entrada' => 0.0,
                'valor_cultural' => 6,
                'palabras_clave' => 'flores,claveles,viveros,noviembre,agricultura',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Concurso de Nacimientos Navideños',
                'tipo_evento' => 'Religioso/Cultural',
                'fecha_inicio' => '2025-12-15',
                'fecha_fin' => '2025-12-25',
                'lugar_asociado' => $idCatedral,
                'afluencia_esperada' => 1500,
                'costo_entrada' => 0.0,
                'valor_cultural' => 7,
                'palabras_clave' => 'navidad,nacimientos,pesebres,diciembre,concurso',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // --- 4. Eventos Cívicos y Menores (Rellenando hasta 40) ---
            [
                'nombre_evento' => 'Día del Campesino Tarmeño',
                'tipo_evento' => 'Cívico/Costumbrista',
                'fecha_inicio' => '2025-06-24',
                'fecha_fin' => '2025-06-24',
                'lugar_asociado' => $idPlazaArmas,
                'afluencia_esperada' => 1000,
                'costo_entrada' => 0.0,
                'valor_cultural' => 6,
                'palabras_clave' => 'campesino,agricultura,junio,ofrenda',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Aniversario de la Creación Política de Palca',
                'tipo_evento' => 'Cívico',
                'fecha_inicio' => '2025-04-30',
                'fecha_fin' => '2025-04-30',
                'lugar_asociado' => $idDistritoPalca,
                'afluencia_esperada' => 500,
                'costo_entrada' => 0.0,
                'valor_cultural' => 5,
                'palabras_clave' => 'Palca,aniversario,abril,desfile',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Festividad de la Virgen de la Candelaria',
                'tipo_evento' => 'Religioso',
                'fecha_inicio' => '2025-02-02',
                'fecha_fin' => '2025-02-03',
                'lugar_asociado' => $idCatedral,
                'afluencia_esperada' => 1000,
                'costo_entrada' => 0.0,
                'valor_cultural' => 7,
                'palabras_clave' => 'Candelaria,virgen,febrero,procesión',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Festival Turístico de la Ruta de las Cítricas',
                'tipo_evento' => 'Feria/Ecoturismo',
                'fecha_inicio' => '2025-09-20',
                'fecha_fin' => '2025-09-21',
                'lugar_asociado' => $idDistritoHuasahuasi,
                'afluencia_esperada' => 800,
                'costo_entrada' => 0.0,
                'valor_cultural' => 6,
                'palabras_clave' => 'cítricos,ruta,Huasahuasi,septiembre,frutas,feria',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Exhibición de Danzas Folklóricas de Tarma',
                'tipo_evento' => 'Cultural/Danza',
                'fecha_inicio' => '2025-10-15',
                'fecha_fin' => '2025-10-15',
                'lugar_asociado' => $idPlazaArmas,
                'afluencia_esperada' => 2000,
                'costo_entrada' => 0.0,
                'valor_cultural' => 8,
                'palabras_clave' => 'danza,folklore,chonguinada,muliza,octubre',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Día de la Pachamama (Madre Tierra)',
                'tipo_evento' => 'Costumbrista/Andino',
                'fecha_inicio' => '2025-08-01',
                'fecha_fin' => '2025-08-01',
                'lugar_asociado' => $idTarmatambo,
                'afluencia_esperada' => 500,
                'costo_entrada' => 0.0,
                'valor_cultural' => 7,
                'palabras_clave' => 'pachamama,agosto,andino,ofrenda,Tarmatambo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Festival del Puchero y Jaka Locro',
                'tipo_evento' => 'Gastronómico',
                'fecha_inicio' => '2025-03-01', // Coincide con Carnavales
                'fecha_fin' => '2025-03-05',
                'lugar_asociado' => $idSanPedroCajas,
                'afluencia_esperada' => 1500,
                'costo_entrada' => 0.0,
                'valor_cultural' => 7,
                'palabras_clave' => 'gastronomía,puchero,jaka locro,San Pedro de Cajas,carnaval',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Aniversario de la Creación Política de Huaricolca',
                'tipo_evento' => 'Cívico',
                'fecha_inicio' => '2025-11-14',
                'fecha_fin' => '2025-11-14',
                'lugar_asociado' => $idDistritoHuaricolca,
                'afluencia_esperada' => 400,
                'costo_entrada' => 0.0,
                'valor_cultural' => 5,
                'palabras_clave' => 'Huaricolca,aniversario,noviembre,desfile',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Día Central de la Inmaculada Concepción',
                'tipo_evento' => 'Religioso',
                'fecha_inicio' => '2025-12-08',
                'fecha_fin' => '2025-12-09',
                'lugar_asociado' => $idCatedral,
                'afluencia_esperada' => 2500,
                'costo_entrada' => 0.0,
                'valor_cultural' => 7,
                'palabras_clave' => 'Inmaculada,diciembre,procesión,virgen',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Feria de la Flor y la Planta Ornamental',
                'tipo_evento' => 'Feria/Comercial',
                'fecha_inicio' => '2025-10-05',
                'fecha_fin' => '2025-10-08',
                'lugar_asociado' => $idCampinaFlores,
                'afluencia_esperada' => 3000,
                'costo_entrada' => 0.0,
                'valor_cultural' => 7,
                'palabras_clave' => 'flor,ornamental,octubre,comercial,viveros',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Aniversario de la Promulgación del Himno Tarmeño',
                'tipo_evento' => 'Cívico/Cultural',
                'fecha_inicio' => '2025-10-12',
                'fecha_fin' => '2025-10-12',
                'lugar_asociado' => $idPlazaArmas,
                'afluencia_esperada' => 300,
                'costo_entrada' => 0.0,
                'valor_cultural' => 5,
                'palabras_clave' => 'himno,octubre,protocolar,cultura',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Fiesta de la Cruz de Tapo',
                'tipo_evento' => 'Religioso',
                'fecha_inicio' => '2025-05-03',
                'fecha_fin' => '2025-05-04',
                'lugar_asociado' => $idDistritoTapo,
                'afluencia_esperada' => 600,
                'costo_entrada' => 0.0,
                'valor_cultural' => 6,
                'palabras_clave' => 'cruz,mayo,Tapo,religión',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Festival del Chicharrón Colorado',
                'tipo_evento' => 'Gastronómico',
                'fecha_inicio' => '2025-08-15',
                'fecha_fin' => '2025-08-17',
                'lugar_asociado' => $idPlazaArmas,
                'afluencia_esperada' => 2500,
                'costo_entrada' => 0.0,
                'valor_cultural' => 6,
                'palabras_clave' => 'chicharrón,gastronomía,agosto,comida típica',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Día Internacional de los Museos (Tarma)',
                'tipo_evento' => 'Educativo/Cultural',
                'fecha_inicio' => '2025-05-18',
                'fecha_fin' => '2025-05-18',
                'lugar_asociado' => $idMuseoOdria,
                'afluencia_esperada' => 400,
                'costo_entrada' => 0.0, // Entrada gratuita
                'valor_cultural' => 5,
                'palabras_clave' => 'museo,cultura,mayo,historia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Festival de Danzas de la Sierra y Selva',
                'tipo_evento' => 'Folclórico',
                'fecha_inicio' => '2025-11-20',
                'fecha_fin' => '2025-11-22',
                'lugar_asociado' => $idPlazaArmas,
                'afluencia_esperada' => 1800,
                'costo_entrada' => 0.0,
                'valor_cultural' => 8,
                'palabras_clave' => 'danzas,folclore,sierra,selva,noviembre,concurso',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Aniversario de la Creación Política de Tapo',
                'tipo_evento' => 'Cívico',
                'fecha_inicio' => '2025-01-02',
                'fecha_fin' => '2025-01-02',
                'lugar_asociado' => $idDistritoTapo,
                'afluencia_esperada' => 300,
                'costo_entrada' => 0.0,
                'valor_cultural' => 5,
                'palabras_clave' => 'Tapo,aniversario,enero,desfile',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Fiesta de la Exaltación de la Santa Cruz (Tarma)',
                'tipo_evento' => 'Religioso',
                'fecha_inicio' => '2025-09-14',
                'fecha_fin' => '2025-09-15',
                'lugar_asociado' => $idCatedral,
                'afluencia_esperada' => 1000,
                'costo_entrada' => 0.0,
                'valor_cultural' => 6,
                'palabras_clave' => 'Santa Cruz,septiembre,procesión,religión',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Día de la Identidad Tarmeña',
                'tipo_evento' => 'Cultural/Cívico',
                'fecha_inicio' => '2025-03-29',
                'fecha_fin' => '2025-03-29',
                'lugar_asociado' => $idPlazaArmas,
                'afluencia_esperada' => 800,
                'costo_entrada' => 0.0,
                'valor_cultural' => 7,
                'palabras_clave' => 'identidad,marzo,cultura,protocolar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Festival Turístico del Valle del Palcamayo',
                'tipo_evento' => 'Ecoturismo/Comunitario',
                'fecha_inicio' => '2025-05-25',
                'fecha_fin' => '2025-05-27',
                'lugar_asociado' => $idDistritoPalcamayo,
                'afluencia_esperada' => 700,
                'costo_entrada' => 0.0,
                'valor_cultural' => 6,
                'palabras_clave' => 'Palcamayo,valle,turismo,mayo,naturaleza',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Concurso de Platos Típicos (Semana Santa)',
                'tipo_evento' => 'Gastronómico',
                'fecha_inicio' => '2025-04-18', // Viernes Santo
                'fecha_fin' => '2025-04-18',
                'lugar_asociado' => $idPlazaArmas,
                'afluencia_esperada' => 3000,
                'costo_entrada' => 0.0,
                'valor_cultural' => 7,
                'palabras_clave' => 'gastronomía,Semana Santa,platos típicos,concurso,abril',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Festival de Música Andina Contemporánea',
                'tipo_evento' => 'Musical',
                'fecha_inicio' => '2025-09-01',
                'fecha_fin' => '2025-09-03',
                'lugar_asociado' => $idPlazaArmas,
                'afluencia_esperada' => 1200,
                'costo_entrada' => 0.0,
                'valor_cultural' => 6,
                'palabras_clave' => 'música,andina,septiembre,concierto,folclore',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Aniversario de la Creación Política de Huasahuasi',
                'tipo_evento' => 'Cívico',
                'fecha_inicio' => '2025-09-30',
                'fecha_fin' => '2025-09-30',
                'lugar_asociado' => $idDistritoHuasahuasi,
                'afluencia_esperada' => 500,
                'costo_entrada' => 0.0,
                'valor_cultural' => 5,
                'palabras_clave' => 'Huasahuasi,aniversario,septiembre,desfile',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Fiesta Patronal de San Francisco de Asís (Acobamba)',
                'tipo_evento' => 'Religioso/Patronal',
                'fecha_inicio' => '2025-10-04',
                'fecha_fin' => '2025-10-05',
                'lugar_asociado' => $idSantuarioMuruhuay, // Plaza de Acobamba (Cercano)
                'afluencia_esperada' => 900,
                'costo_entrada' => 0.0,
                'valor_cultural' => 6,
                'palabras_clave' => 'San Francisco,Acobamba,octubre,patronal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Juegos Florales y Concurso Literario Tarmeño',
                'tipo_evento' => 'Cultural/Literario',
                'fecha_inicio' => '2025-12-05',
                'fecha_fin' => '2025-12-07',
                'lugar_asociado' => $idMuseoOdria,
                'afluencia_esperada' => 200,
                'costo_entrada' => 0.0,
                'valor_cultural' => 6,
                'palabras_clave' => 'literatura,poesía,juegos florales,diciembre',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Vigilia por el Aniversario de Tarma',
                'tipo_evento' => 'Cívico/Serenata',
                'fecha_inicio' => '2025-07-25',
                'fecha_fin' => '2025-07-26',
                'lugar_asociado' => $idPlazaArmas,
                'afluencia_esperada' => 4000,
                'costo_entrada' => 0.0,
                'valor_cultural' => 7,
                'palabras_clave' => 'serenata,aniversario,música,Julio',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Festival de Deportes de Aventura en el Valle',
                'tipo_evento' => 'Deportivo',
                'fecha_inicio' => '2025-11-10',
                'fecha_fin' => '2025-11-12',
                'lugar_asociado' => $idGrutaHuagapo, // Se utiliza el entorno natural
                'afluencia_esperada' => 500,
                'costo_entrada' => 0.0,
                'valor_cultural' => 5,
                'palabras_clave' => 'ciclismo,trekking,aventura,Palcamayo,noviembre',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Aniversario de la Creación Política de Acobamba',
                'tipo_evento' => 'Cívico',
                'fecha_inicio' => '2025-11-14',
                'fecha_fin' => '2025-11-14',
                'lugar_asociado' => $idSantuarioMuruhuay, // Plaza de Acobamba
                'afluencia_esperada' => 450,
                'costo_entrada' => 0.0,
                'valor_cultural' => 5,
                'palabras_clave' => 'Acobamba,aniversario,noviembre,desfile',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Concurso de Canto y Música Vernacular',
                'tipo_evento' => 'Musical/Folclórico',
                'fecha_inicio' => '2025-04-05',
                'fecha_fin' => '2025-04-06',
                'lugar_asociado' => $idPlazaArmas,
                'afluencia_esperada' => 800,
                'costo_entrada' => 0.0,
                'valor_cultural' => 6,
                'palabras_clave' => 'canto,vernacular,abril,música andina',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Día de la Bandera y Juramento (Tarma)',
                'tipo_evento' => 'Cívico/Protocolar',
                'fecha_inicio' => '2025-06-07',
                'fecha_fin' => '2025-06-07',
                'lugar_asociado' => $idPlazaArmas,
                'afluencia_esperada' => 1500,
                'costo_entrada' => 0.0,
                'valor_cultural' => 5,
                'palabras_clave' => 'Bandera,junio,protocolar,desfile',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Día de la Cocina y Repostería Tarmeña',
                'tipo_evento' => 'Gastronómico',
                'fecha_inicio' => '2025-10-20',
                'fecha_fin' => '2025-10-22',
                'lugar_asociado' => $idPlazaArmas,
                'afluencia_esperada' => 1000,
                'costo_entrada' => 0.0,
                'valor_cultural' => 7,
                'palabras_clave' => 'gastronomía,repostería,octubre,cocina',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Fiesta de los Reyes Magos (Bajada de Reyes)',
                'tipo_evento' => 'Religioso',
                'fecha_inicio' => '2025-01-06',
                'fecha_fin' => '2025-01-06',
                'lugar_asociado' => $idCatedral,
                'afluencia_esperada' => 1000,
                'costo_entrada' => 0.0,
                'valor_cultural' => 6,
                'palabras_clave' => 'Reyes Magos,enero,religión',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_evento' => 'Trekking Histórico a Tarmatambo y Colcas',
                'tipo_evento' => 'Deportivo/Ecoturismo',
                'fecha_inicio' => '2025-05-10',
                'fecha_fin' => '2025-05-11',
                'lugar_asociado' => $idTarmatambo,
                'afluencia_esperada' => 400,
                'costo_entrada' => 0.0,
                'valor_cultural' => 6,
                'palabras_clave' => 'trekking,Tarmatambo,colcas,mayo,caminata',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
